CREATE TABLE todos
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    description  VARCHAR(255),
    is_completed BOOLEAN,
    CONSTRAINT pk_todos PRIMARY KEY (id)
);